version: 0.2
env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-cred/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-cred/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url
    
phases:
  pre_build:
    commands:
      - echo "INSTALLING DEPENDENCIES"
      - pip install -r requirement.txt
  build:
    commands:
      - echo "CREATING IMAGE!!"
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/image2:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/image2:latest"
  post_build:
    commands:
      - echo "COMPLETED!!!"
      
artifacts:
  files:
    - '**/*'
    - 'out/**/*'
    - 'scripts/**/*'

